[[plugins]]
repository = 'Shougo/tabpagebuffer.vim'
on_ft = 'all'

[[plugins]]
repository = 'Shougo/neopairs.vim'
on_i = 1

[[plugins]]
repository = 'Shougo/neomru.vim'
on_ft = 'all'

[[plugins]]
repository = 'Shougo/echodoc.vim'
on_i = 1

[[plugins]]
repository = 'Shougo/neocomplete.vim'
depends = 'Shougo/context_filetype.vim'
on_i = 1

[[plugins]]
repository = 'Shougo/deoplete.nvim'
depends = 'Shougo/context_filetype.vim'
on_i = 1

[[plugins]]
repository = 'Shougo/neosnippet.vim'
depends = ['Shougo/neosnippet-snippets', 'Shougo/context_filetype.vim']
on_i = 1
on_ft = 'snippet'
on_unite = ['neosnippet', 'neosnippet/user', 'neosnippet/runtime']

[[plugins]]
repository = 'Shougo/unite.vim'
depends = 'Shougo/neomru.vim'

  [plugins.on_cmd]
  name = 'Unite'
  complete = 'customlist,unite#complete_source'

[[plugins]]
repository = 'Shougo/unite-build'

[[plugins]]
repository = 'Shougo/neossh.vim'
on_ft = ['vimfiler', 'vimshell']
sources = 'ssh'

[[plugins]]
repository = 'Shougo/vimfiler.vim'
depends = 'Shougo/unite.vim'
on_map = '<Plug>'
on_path = '.*'

  [plugins.on_cmd]
  name = ['VimFiler']
  complete = 'customlist,vimfiler#complete'

[[plugins]]
repository = 'Shougo/vimshell.vim'
on_map = '<Plug>'

  [plugins.on_cmd]
  name = 'VimShell'
  complete = 'customlist,vimshell#complete'

[[plugins]]
repository = 'Shougo/junkfile.vim'
on_unite = 'junkfile'

[[plugins]]
repository = 'Shougo/unite-outline'

[[plugins]]
repository = 'Shougo/unite-sudo'

[[plugins]]
repository = 'Shougo/unite-help'

[[plugins]]
repository = 'Shougo/neco-vim'
on_ft = 'vim'
on_i = 1

[[plugins]]
repository = 'Shougo/neoinclude.vim'
on_ft = 'all'

[[plugins]]
repository = 'Shougo/neco-syntax'
on_i = 1

[[plugins]]
repository = 'Shougo/vinarise.vim'

  [plugins.on_cmd]
  name = 'Vinarise'
  complete = 'file'

[[plugins]]
repository = 'kana/vim-niceblock'
on_map = '<Plug>'

[[plugins]]
repository = 'ujihisa/vimshell-ssh'
on_ft = 'vimshell'

[[plugins]]
repository = 'yomi322/vim-gitcomplete'
on_ft = 'vimshell'

[[plugins]]
repository = 'vim-jp/vital.vim'
on_cmd = 'Vitalize'

[[plugins]]
repository = 'hail2u/vim-css3-syntax'

[[plugins]]
repository = 'kana/vim-smartchr'
on_i = 1

[[plugins]]
repository = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repository = 'LeafCage/foldCC'
on_ft = 'vim'

[[plugins]]
repository = 'mattn/webapi-vim'

[[plugins]]
repository = 'thinca/vim-fontzoom'
gui = 1
on_map = '<Plug>'

[[plugins]]
repository = 'thinca/vim-prettyprint'
on_cmd = 'PP'

[[plugins]]
repository = 'thinca/vim-qfreplace'
on_ft = ['unite', 'quickfix']

[[plugins]]
repository = 'thinca/vim-quickrun'
on_map = '<Plug>'

[[plugins]]
repository = 'thinca/vim-scouter'

[[plugins]]
repository = 'thinca/vim-ref'
on_unite = 'ref'

[[plugins]]
repository = 'thinca/vim-unite-history'

[[plugins]]
repository = 'vim-ruby/vim-ruby'
on_map = '<Plug>'
on_ft = 'ruby'

[[plugins]]
repository = 'basyura/J6uil.vim'
on_unite = 'J6uil'
depends = 'mattn/webapi-vim'

  [plugins.on_cmd]
  name = 'J6uil'
  complete = 'custom,J6uil#complete#room'

[[plugins]]
repository = 'tsukkee/unite-tag'

[[plugins]]
repository = 'tyru/caw.vim'
on_map = '<Plug>'

[[plugins]]
repository = 'tyru/eskk.vim'
on_map = [['i', '<Plug>'], ['c', '<Plug>']]

[[plugins]]
repository = 'tyru/open-browser.vim'
on_map = '<Plug>'

[[plugins]]
repository = 'tyru/restart.vim'
gui = 1
on_cmd = 'Restart'

[[plugins]]
repository = 'tyru/winmove.vim'
on_map = '<Plug>'
gui = 1
augroup = 'winmove'

[[plugins]]
repository = 'eagletmt/neco-ghc'
on_ft = 'haskell'
external_commands = 'ghc-mod'

[[plugins]]
repository = 'ujihisa/neco-look'
on_i = 1

[[plugins]]
repository = 'ujihisa/unite-colorscheme'

[[plugins]]
repository = 'vim-jp/vimdoc-ja'
on_ft = 'help'

#[[plugins]]
#repository = 'eignn/netrw.vim'
#on_cmd = 'Explore'

[[plugins]]
repository = 'osyo-manga/unite-quickfix'

[[plugins]]
repository = 'osyo-manga/unite-filetype'

[[plugins]]
repository = 'kana/vim-tabpagecd'
on_unite = 'tab'

[[plugins]]
repository = 'rhysd/accelerated-jk'
on_map = '<Plug>'

[[plugins]]
repository = 'vim-jp/autofmt'

[[plugins]]
repository = 'supermomonga/unite-kawaii-calc'

[[plugins]]
repository = 'godlygeek/csapprox'
terminal = 1

[[plugins]]
repository = 'thinca/vim-guicolorscheme'
terminal = 1

[[plugins]]
repository = 'benjifisher/matchit.zip'
on_map = [['nxo', '%', 'g%']]

[[plugins]]
repository = 'jiangmiao/simple-javascript-indenter'
on_ft = 'javascript'

[[plugins]]
repository = 'jelera/vim-javascript-syntax'
on_ft = 'javascript'

[[plugins]]
repository = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repository = 'bkad/CamelCaseMotion'
on_map = ['<Plug>CamelCaseMotion_w', '<Plug>CamelCaseMotion_b']

[[plugins]]
repository = 'aharisu/vim-gdev'
on_ft = 'scheme'

[[plugins]]
repository = 'vim-jp/cpp-vim'
on_ft = 'cpp'

[[plugins]]
repository = 'thinca/vim-ft-diff_fold'
on_ft = 'diff'

[[plugins]]
repository = 'nsf/gocode'
rtp = 'vim'
on_ft = 'go'

[[plugins]]
repository = 'thinca/vim-ft-help_fold'
on_ft = 'help'

[[plugins]]
repository = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repository = 'kana/vim-filetype-haskell'
on_ft = 'haskell'

[[plugins]]
repository = 'JesseKPhillips/d.vim'
on_ft = 'd'

[[plugins]]
repository = 't9md/vim-choosewin'
on_map = '<Plug>'

[[plugins]]
repository = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repository = 'lambdalisue/vim-fullscreen'
gui = 1
on_map = '<Plug>'

[[plugins]]
repository = 'todesking/ruby_hl_lvar.vim'
on_ft = 'ruby'

[[plugins]]
repository = 'syngan/vim-vimlint'
depends = 'ynkdir/vim-vimlparser'

# Operators
[[plugins]]
repository = 'kana/vim-operator-user'

[[plugins]]
repository = 'kana/vim-operator-replace'
depends = 'kana/vim-operator-user'
on_map = [['nx', '<Plug>']]

[[plugins]]
repository = 'rhysd/vim-operator-surround'
depends = 'kana/vim-operator-user'
on_map = '<Plug>'

[[plugins]]
repository = 'chikatoike/concealedyank.vim'
on_map = [['x', '<Plug>(operator-concealedyank)']]

# Textobjs
[[plugins]]
repository = 'kana/vim-textobj-user'

[[plugins]]
repository = 'osyo-manga/vim-textobj-multiblock'
depends = 'kana/vim-textobj-user'
on_map = [['ox', '<Plug>']]

[[plugins]]
repository = 'AndrewRadev/sideways.vim'
on_map = [['ox', '<Plug>']]

[[plugins]]
repository = 'saihoooooooo/glowshi-ft.vim'
on_map = '<Plug>'

[[plugins]]
repository = 'Rykka/riv.vim'
on_ft = 'rst'

[[plugins]]
repository = 'rcmdnk/vim-markdown'
on_ft = ['markdown', 'mkd']

[[plugins]]
repository = 'kannokanno/previm'
on_ft = ['markdown', 'rst', 'mkd']
depends = 'tyru/open-browser.vim'

[[plugins]]
repository = 'Kocha/vim-unite-tig'

[[plugins]]
repository = 'osyo-manga/vim-jplus'
on_map = '<Plug>'

[[plugins]]
repository = 'osyo-manga/unite-vimpatches'

[[plugins]]
repository = 'katono/rogue.vim'
on_cmd = 'Rogue'

[[plugins]]
repository = 'sorah/unite-ghq'

[[plugins]]
repository = 'thinca/vim-themis'
on_ft = 'vim'

[[plugins]]
repository = 'osyo-manga/vim-monster'
on_ft = 'ruby'

[[plugins]]
repository = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repository = 'lambdalisue/vim-gita'
on_cmd = 'Gita'

[[plugins]]
repository = 'lambdalisue/vim-gista'
on_cmd = 'Gista'
on_map = '<Plug>'
on_unite = 'gista'
# rev = 'release'

[[plugins]]
repository = 'davidhalter/jedi-vim'
on_ft = 'python'

[[plugins]]
repository = 'terryma/vim-expand-region'
on_map = [['x', '<Plug>']]

[[plugins]]
repository = 'phildawes/racer'
on_ft = 'rust'

[[plugins]]
repository = 'rust-lang/rust.vim'
on_ft = 'rust'

[[plugins]]
repository = 'rhysd/rust-doc.vim'
on_ft = 'rust'

[[plugins]]
repository = 'shawncplus/phpcomplete.vim'
on_ft = 'php'

[[plugins]]
repository = 'marijnh/tern_for_vim'
on_ft = 'javascript'
build = 'npm install'

[[plugins]]
repository = 'mxw/vim-jsx'
on_ft = 'javascript'

[[plugins]]
repository = 'osyo-manga/vim-marching'
on_ft = ['c', 'cpp']

[[plugins]]
repository = 'artur-shaik/vim-javacomplete2'
on_ft = 'java'

[[plugins]]
repository = 'rhysd/committia.vim'
on_path = 'COMMIT_EDITMSG'

[[plugins]]
repository = 'itchyny/vim-haskell-indent'
on_ft = 'haskell'

[[plugins]]
repository = 'lambdalisue/vim-findent'
on_path = '.*'

[[plugins]]
repository = 'udalov/kotlin-vim'
on_ft = 'kotlin'

[[plugins]]
repository = 'Konfekt/FastFold'
on_path = '.*'

[[plugins]]
repository = 'xolox/vim-lua-ftplugin'
depends = 'xolox/vim-misc'
on_ft = 'lua'

